//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.Net._7.DataBaseFirst.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableEquipmentHistory
    {
        public int intEquipmentHistoryId { get; set; }
        public Nullable<int> intEquipmentID { get; set; }
        public Nullable<int> intTypeHistory { get; set; }
        public Nullable<System.DateTime> dStartDate { get; set; }
        public Nullable<System.DateTime> dEndDate { get; set; }
        public Nullable<int> intDaysCount { get; set; }
        public Nullable<int> intStatys { get; set; }
        public Nullable<int> intUserId { get; set; }
        public Nullable<System.DateTime> dCahengeDate { get; set; }
    
        public virtual newEquipment newEquipment { get; set; }
    }
}
