//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.Net._7.DataBaseFirst.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackMeter
    {
        public int intMeteredId { get; set; }
        public int intEquipmentID { get; set; }
        public System.DateTime dMeterDate { get; set; }
        public double intMeterReading { get; set; }
        public Nullable<double> intHoursHoursOperation { get; set; }
        public Nullable<double> intTotalMeter { get; set; }
        public bool boolMeterReplaced { get; set; }
        public int intTypeMetered { get; set; }
        public Nullable<int> intComponentId { get; set; }
        public Nullable<int> intLocationId { get; set; }
    
        public virtual newEquipment newEquipment { get; set; }
    }
}
