//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.Net._7.ModelFirst.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablesModel
    {
        public int intModelID { get; set; }
        public string strName { get; set; }
        public Nullable<int> intManufacturerID { get; set; }
        public Nullable<int> intSMCSFamilyID { get; set; }
        public string strImage { get; set; }
    
        public virtual TablesManufacturer TablesManufacturer { get; set; }
    }
}
